error = ['test','test1']
#print(error[3])#index 3 doenst exit
error.append('perro')
print(error.insert(2,'indexer'))
print(error)